# .github/workflows/full-market-open.yml
# Full update at market open
name: Full Stock Update (Market Open)

on:
  schedule:
    # Monday-Friday at 9:29 AM ET (13:29 UTC for EST, 14:29 UTC for EDT)
    # Using 13:29 UTC (EST)
    - cron: '29 13 * * 1-5'
  workflow_dispatch:

jobs:
  full-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Full Market Open Update
        run: |
          echo "Starting full market open update..."
          
          response=$(curl -s -w "\n%{http_code}" -X POST \
            "${{ secrets.SUPABASE_FUNCTIONS_URL }}/update-stocks?mode=full" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}')
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          echo "Response: $body"
          
          # Parse response
          updated=$(echo "$body" | jq -r '.updated // 0')
          duration=$(echo "$body" | jq -r '.duration_readable // "unknown"')
          
          echo "Updated $updated stocks in $duration"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "Full update failed! Check logs."
          # Add Slack/Discord/Email notification here if needed
